name: Labels
permissions: read-all
on: [issues, pull_request]
jobs:
  sync-labels:
    permissions:
        issues: write
    runs-on: ubuntu-latest
    name: Sync Labels
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set Labels
        uses: outoforbitdev/action-label-manager@897d4a477652b8a84782bff1c8894a631d7c2097 # v0.0.1
        id: set-labels
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
