name: Labels
permissions: read-all
on: [issues, pull_request]
jobs:
  sync-labels:
    permissions:
        issues: write
    runs-on: ubuntu-latest
    name: Sync Labels
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set Labels
        uses: outoforbitdev/action-label-manager@f24babe4b405f7926996b5a42bbc4ae3b962dd4e # v0.0.1
        id: set-labels
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
