name: Sync Labels
on:
  issues: 
    types:
      - opened
      - labeled
  pull_request:
    types:
      - opened
      - labeled

# Declare default permissions as read only.
permissions: read-all

jobs:
  labels:
    uses: outoforbitdev/reusable-workflows-library/.github/workflows/label-manager.yml@946b588a1dca9f4c9e344b1c586f333b6384312d # v1.0.0
    permissions:
      issues: write
